GET http://localhost:3003/api/blogs/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvZmxrb3B0ZXJpIiwiaWQiOiI2MWE2NDBkYjY4ZTY1NmQ0OGFjMDk3MTkiLCJpYXQiOjE2MzgyODU1NDZ9.9GqmkeJXr8XvsYrASqTUtuWwXlHv6sLtaGbljFtzFLE 