GET http://localhost:3003/api/blogs/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvbnQgY2FyZSIsImlkIjoiNjFhNjNmNmRmY2MxNjRmYzE1YTM2OWQxIiwiaWF0IjoxNjM4Mjg1MjY4fQ.Dq5ioewsQGIbN-o0zpyRnVIFqSlPSH-lru8hFnxcQGg